### ISSUE TITLE
使用FOSSA对项目的进行供应链安全扫描，发现有依赖存在合规问题，来源于antd相关组件的使用到的这个库，虽然commit记录显示已添加LICENSE，不过并未发版

### ISSUE THREAD

**Issue by MatrixAge** [chenshuai2144/sketch-color#4]
![image](https://user-images.githubusercontent.com/25472851/215411266-bed4a66d-3308-4899-be15-7cd7fde3a312.png)

如果可以的话，发一版带LICENSE的，给Antd 4.*（5.*我不知道有没有用这个库）升级到带LICENSE的。

感谢🙏。

**Comment by sansheng741** [comment]
antd5也用到了，也是没有license

**Comment by chenshuai2144** [comment]
来个pr吧

**Comment by MatrixAge** [comment]
> 来个pr吧

仓库代码里是有lisence的，只是没有发版
